substitutions:
  device_name: "hdmi-matrix"
  friendly_name: "HDMI Matrix"

packages:
  device: !include
    file: devices/sonoff-s2x.yaml
    vars:
      restore_mode: RESTORE_DEFAULT_OFF
  location: !include common/house.yaml
