substitutions:
  device_name: "jacksons-room-light"
  friendly_name: "Jacksons Room Light"
  max_temp: "70" # °C

<<: !include common/base.yaml
<<: !include common/house.yaml
<<: !include devices/shelly-dimmer2.yaml
