substitutions:
  device_name: "laundry-light"
  friendly_name: "Laundry Light"
  channel_1: "Laundry Light"
  channel_2: "Roof Light"

packages:
  device: !include devices/shelly-25.yaml
  location: !include common/house.yaml
