substitutions:
  device_name: "lounge-light"
  friendly_name: "Lounge Light"
  max_temp: "70" # °C

<<: !include common/base.yaml
<<: !include common/house.yaml
<<: !include devices/shelly-dimmer2.yaml
