substitutions:
  device_name: "shed-fan"
  friendly_name: "Shed Fan"

<<: !include common/base.yaml
<<: !include common/shed.yaml
<<: !include
  file: devices/athom-smart-plug-v2.yaml
  vars:
    relay_restore_mode: RESTORE_DEFAULT_OFF
