substitutions:
  device_name: "shed-heater"
  friendly_name: "Shed Heater"

<<: !include common/base.yaml
<<: !include common/shed.yaml
<<: !include
  file: devices/athom-smart-plug-v2.yaml
  vars:
    relay_restore_mode: RESTORE_DEFAULT_OFF
