substitutions:
  device_name: "shed-light"
  friendly_name: "Shed Light"
  channel_1: "Shed Light"
  channel_2: "Carport Light"

packages:
  device: !include devices/shelly-25.yaml
  location: !include common/shed.yaml
