substitutions:
  comment: Arlec Smart Boston Fan
  light_restore_mode: ALWAYS_OFF

packages:
  common: !include ../common/base.yaml

esp8266:
  board: esp01_1m

uart:
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600

tuya:

fan:
- platform: "tuya"
  name: "Fan"
  switch_datapoint: 1
  speed_datapoint: 3
  direction_datapoint: 4
  speed_count: 6

light:
- platform: "tuya"
  name: "Light"
  switch_datapoint: 9
  dimmer_datapoint: 10
  min_value: 0
  max_value: 100
  color_temperature_datapoint: 11
  color_temperature_max_value: 100
  cold_white_color_temperature: 150 mireds
  warm_white_color_temperature: 400 mireds
  restore_mode: ${light_restore_mode}
