substitutions:
  comment: Sonoff S2X
  restore_mode: ALWAYS_OFF

packages:
  common: !include ../common/base.yaml

esp8266:
  board: esp01_1m

status_led:
  pin:
    number: GPIO13
    inverted: false

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Button"
  internal: true
  on_press:
  - switch.toggle: relay

switch:
- platform: gpio
  name: "Relay"
  pin: GPIO12
  id: "relay"
  restore_mode: ${restore_mode}
