substitutions:
  comment: Sonoff Mini

packages:
  common: !include ../common/base.yaml

esp8266:
  board: esp01_1m

binary_sensor:
# the 7 lines below define the reset button
- platform: gpio
  pin: GPIO00
  id: reset
  internal: true # hides reset switch from HomeAssistant
  filters:
  - invert:
  - delayed_off: 10ms
  # the 3 lines below toggle the main relay on press of reset button
  on_press:
  - light.toggle:
      id: light_id

# the 13 lines below toggle the main relay on command
- platform: gpio
  name: relay_toggle
  internal: true # hides relay toggle from HomeAssistant
  pin: GPIO04
  id: gpio_light_id
  on_press:
    then:
    - light.toggle:
        id: light_id
  on_release:
    then:
    - light.toggle:
        id: light_id

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
# the 3 lines below control the main relay
- platform: gpio
  pin: GPIO12
  id: main_light_relay
- platform: esp8266_pwm
  # the 3 lines below control the Blue LED
  id: blue_led
  pin: GPIO13
  inverted: True

light:
# the 4 lines below define the main relay as a light
- platform: binary
  name: Relay
  output: main_light_relay
  id: light_id
- platform: monochromatic
  # the 4 lines below define the Blue LED light on Sonoff Mini, to expose in HomeAssistant remove line "internal: true"
  name: ${device_name}_blueled
  output: blue_led
  internal: true # hides the Blue LED from Homeassistant
