substitutions:
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password
  comment: ""

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: 15min
  encryption:
    key: ${api_key}

ota:
  platform: esphome
  password: ${ota_password}

captive_portal:

# Enable Web server
web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time

sensor:
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: restart
    name: "Restart"
    id: restart_button
